# fly.toml file generated for diffusion-bot-rust on 2022-12-10T12:45:53-08:00

app = "diffusion-bot-rust"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
# required because we can't infer your binary's name
cmd = "diffusion-bot-rust"
